///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace test_uygulamasi
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("973aaab2-8d39-44bc-a7c7-b7e8a6f1512b", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the test_uygulamasiRepository repository.
        /// </summary>
        public static test_uygulamasiRepository repo = test_uygulamasiRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://demo.borland.com/InsuranceWebExtJS/index.jsf' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://demo.borland.com/InsuranceWebExtJS/index.jsf", "chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 1078;221.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(1));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.Click("1078;221");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 951;168.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(2));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.Click("951;168");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'john' with focus on 'OPTiiMWebApplicationGoogleChrome'.", repo.OPTiiMWebApplicationGoogleChrome.SelfInfo, new RecordItemIndex(3));
            repo.OPTiiMWebApplicationGoogleChrome.Self.PressKeys("john");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '.smith{LControlKey down}{RMenu down}{Qkey}{LControlKey up}{RMenu up}{Gkey}{Mkey}{LControlKey up}ail.com' with focus on 'InsuranceWebHomeGoogleChrome'.", repo.InsuranceWebHomeGoogleChromeInfo, new RecordItemIndex(4));
            repo.InsuranceWebHomeGoogleChrome.PressKeys(".smith{LControlKey down}{RMenu down}{Qkey}{LControlKey up}{RMenu up}{Gkey}{Mkey}{LControlKey up}ail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 947;192.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(5));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.Click("947;192");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'john' with focus on 'InsuranceWebHomeGoogleChrome'.", repo.InsuranceWebHomeGoogleChromeInfo, new RecordItemIndex(6));
            repo.InsuranceWebHomeGoogleChrome.PressKeys("john");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 884;220.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(7));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.Click("884;220");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DoYouWantGoogleSmartLockToSaveYo.Never' at 23;12.", repo.DoYouWantGoogleSmartLockToSaveYo.NeverInfo, new RecordItemIndex(8));
            repo.DoYouWantGoogleSmartLockToSaveYo.Never.Click("23;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 889;108.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(9));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.Click("889;108");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 54;81.", repo.Dropdown.SelfInfo, new RecordItemIndex(10));
            repo.Dropdown.Self.Click("54;81");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 489;96.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(11));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.Click("489;96");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 482;88.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(12));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.Click("482;88");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 904;91.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(13));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.Click("904;91");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 42;30.", repo.Dropdown.SelfInfo, new RecordItemIndex(14));
            repo.Dropdown.Self.Click("42;30");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 731;282.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(15));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.Click("731;282");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}{NumPad2}{NumPad3}' with focus on 'OPTiiMWebApplicationGoogleChrome'.", repo.OPTiiMWebApplicationGoogleChrome.SelfInfo, new RecordItemIndex(16));
            repo.OPTiiMWebApplicationGoogleChrome.Self.PressKeys("{NumPad1}{NumPad2}{NumPad3}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 696;327.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(17));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.Click("696;327");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'adfasdf{LControlKey down}{RMenu down}{Qkey}{LControlKey up}{RMenu up}{LControlKey up}asdf.com' with focus on 'InsuranceWebAutomobileInstantQuote'.", repo.InsuranceWebAutomobileInstantQuoteInfo, new RecordItemIndex(18));
            repo.InsuranceWebAutomobileInstantQuote.PressKeys("adfasdf{LControlKey down}{RMenu down}{Qkey}{LControlKey up}{RMenu up}{LControlKey up}asdf.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 654;351.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(19));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.Click("654;351");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 681;385.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(20));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.Click("681;385");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 681;252.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(21));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.Click("681;252");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 681;252.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(22));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.MoveTo("681;252");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 647;259.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(23));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.MoveTo("647;259");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}{NumPad9}' with focus on 'InsuranceWebAutomobileInstantQuote'.", repo.InsuranceWebAutomobileInstantQuoteInfo, new RecordItemIndex(24));
            repo.InsuranceWebAutomobileInstantQuote.PressKeys("{NumPad1}{NumPad9}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 654;285.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(25));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.Click("654;285");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 653;331.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(26));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.Click("653;331");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 680;401.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(27));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.Click("680;401");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 690;249.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(28));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.MoveTo("690;249");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 633;263.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(29));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.MoveTo("633;263");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad6}{NumPad0}' with focus on 'InsuranceWebAutomobileInstantQuote'.", repo.InsuranceWebAutomobileInstantQuoteInfo, new RecordItemIndex(30));
            repo.InsuranceWebAutomobileInstantQuote.PressKeys("{NumPad6}{NumPad0}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 780;287.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(31));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.Click("780;287");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 698;345.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(32));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.Click("698;345");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 777;326.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(33));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.Click("777;326");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 676;440.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(34));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.Click("676;440");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 653;358.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(35));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.Click("653;358");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 694;425.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(36));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.Click("694;425");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 673;256.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(37));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.MoveTo("673;256");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 646;256.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(38));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.MoveTo("646;256");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}{NumPad9}{NumPad9}{NumPad7}' with focus on 'InsuranceWebAutomobileInstantQuote'.", repo.InsuranceWebAutomobileInstantQuoteInfo, new RecordItemIndex(39));
            repo.InsuranceWebAutomobileInstantQuote.PressKeys("{NumPad1}{NumPad9}{NumPad9}{NumPad7}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 686;424.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(40));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.Click("686;424");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OPTiiMWebApplicationGoogleChrome.Element730569856' at 636;533.", repo.OPTiiMWebApplicationGoogleChrome.Element730569856Info, new RecordItemIndex(41));
            repo.OPTiiMWebApplicationGoogleChrome.Element730569856.Click("636;533");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
