///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace test_uygulamasi
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("973aaab2-8d39-44bc-a7c7-b7e8a6f1512b", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the test_uygulamasiRepository repository.
        /// </summary>
        public static test_uygulamasiRepository repo = test_uygulamasiRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Program Files\\SoftEther VPN Client\\vpncmgr.exe' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Program Files\\SoftEther VPN Client\\vpncmgr.exe", "", "C:\\Program Files\\SoftEther VPN Client", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SoftEtherVPNClientManager.Edit' at 21;13.", repo.SoftEtherVPNClientManager.EditInfo, new RecordItemIndex(1));
            repo.SoftEtherVPNClientManager.Edit.Click("21;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vpncmgr.SelectAllCtrlPlusA' at 22;18.", repo.Vpncmgr.SelectAllCtrlPlusAInfo, new RecordItemIndex(2));
            repo.Vpncmgr.SelectAllCtrlPlusA.Click("22;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SoftEtherVPNClientManager.Tools' at 16;6.", repo.SoftEtherVPNClientManager.ToolsInfo, new RecordItemIndex(3));
            repo.SoftEtherVPNClientManager.Tools.Click("16;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vpncmgr.OptionsCtrlPlusO' at 49;12.", repo.Vpncmgr.OptionsCtrlPlusOInfo, new RecordItemIndex(4));
            repo.Vpncmgr.OptionsCtrlPlusO.Click("49;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OptionalSettings.AllowRemoteManagementOfVPNClientSe' at 16;7.", repo.OptionalSettings.AllowRemoteManagementOfVPNClientSeInfo, new RecordItemIndex(5));
            repo.OptionalSettings.AllowRemoteManagementOfVPNClientSe.Click("16;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OptionalSettings.Cancel' at 52;5.", repo.OptionalSettings.CancelInfo, new RecordItemIndex(6));
            repo.OptionalSettings.Cancel.Click("52;5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SoftEtherVPNClientManager.Connect' at 35;12.", repo.SoftEtherVPNClientManager.ConnectInfo, new RecordItemIndex(7));
            repo.SoftEtherVPNClientManager.Connect.Click("35;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Vpncmgr.ExitConnectionManagerProgramAltPlusQ' at 48;12.", repo.Vpncmgr.ExitConnectionManagerProgramAltPlusQInfo, new RecordItemIndex(8));
            repo.Vpncmgr.ExitConnectionManagerProgramAltPlusQ.Click("48;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SoftEtherVPNClientManager.ButtonYes' at 48;15.", repo.SoftEtherVPNClientManager.ButtonYesInfo, new RecordItemIndex(9));
            repo.SoftEtherVPNClientManager.ButtonYes.Click("48;15");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
